import fs from 'node:fs/promises'
import path from 'node:path'
import type { ServerResponse } from 'node:http'
import type { Plugin } from 'vite'

type MapsJson = {
  maps: Array<{ id: string; displayName: string; fieldType: string; sourceUrl: string | null }>
  mobSpawns: Record<string, unknown[]>
  portals?: Record<
    string,
    Array<{
      id: string
      x: number
      y: number
      width: number
      height: number
      targetMapId: string
      targetX: number
      targetY: number
      label: string
      mode: string
    }>
  >
}

type PortalEntry = NonNullable<MapsJson['portals']>[string][number]

type SaveBody = {
  mapMeta: { id: string; displayName: string; fieldType: string; sourceUrl: string | null }
  tmj: unknown
  portals: PortalEntry[]
}

function isLocalhostHost(host: string | undefined): boolean {
  if (!host) return false
  const h = host.split(':')[0]
  return h === 'localhost' || h === '127.0.0.1' || h === '[::1]'
}

function json(res: ServerResponse, status: number, body: unknown) {
  res.statusCode = status
  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify(body))
}

async function readJsonFile<T>(filePath: string): Promise<T> {
  const raw = await fs.readFile(filePath, 'utf8')
  return JSON.parse(raw) as T
}

function buildMapPortalsExport(mapsJson: MapsJson): { portals: MapsJson['portals'] } {
  const out: NonNullable<MapsJson['portals']> = {}
  const all = mapsJson.portals ?? {}
  for (const [mapId, list] of Object.entries(all)) {
    const walk = list.filter((p) => p.mode === 'walk' || p.mode === 'both')
    if (walk.length > 0) out[mapId] = walk
  }
  return { portals: out }
}

function escapeSqlString(s: string): string {
  return s.replace(/'/g, "''")
}

function generateNpcSql(mapId: string, portals: PortalEntry[]): string {
  const npcPortals = portals.filter((p) => p.mode === 'npc' || p.mode === 'both')
  if (npcPortals.length === 0) return '-- No NPC teleport portals on this map'

  const lines: string[] = [
    `-- NPC teleports for map ${mapId} (generated by map admin)`,
    'insert into public.npc_definitions (id, map_id, x, y, npc_type, label, config)',
    'values',
  ]

  const values = npcPortals.map((p) => {
    const cx = Math.round(p.x + p.width / 2)
    const cy = Math.round(p.y + p.height / 2)
    const npcId = `${mapId}_${p.id}`
    const config = JSON.stringify({
      destinations: [
        {
          map_id: p.targetMapId,
          label: p.label,
          x: p.targetX,
          y: p.targetY,
        },
      ],
    })
    return `  (
    '${escapeSqlString(npcId)}',
    '${escapeSqlString(mapId)}',
    ${cx},
    ${cy},
    'teleport',
    '${escapeSqlString(p.label)}',
    '${escapeSqlString(config)}'::jsonb
  )`
  })

  lines.push(values.join(',\n'))
  lines.push(`on conflict (id) do update set
  map_id = excluded.map_id,
  x = excluded.x,
  y = excluded.y,
  npc_type = excluded.npc_type,
  label = excluded.label,
  config = excluded.config;`)

  return lines.join('\n')
}

export function mapAdminApiPlugin(repoRoot: string): Plugin {
  const mapsJsonPath = path.join(repoRoot, 'content/ro/maps.json')
  const mapsDir = path.join(repoRoot, 'client/public/maps')
  const sharedPortalsPath = path.join(repoRoot, 'supabase/functions/_shared/mapPortals.json')

  return {
    name: 'map-admin-api',
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        if (!req.url?.startsWith('/__admin/maps')) {
          next()
          return
        }

        if (!isLocalhostHost(req.headers.host)) {
          json(res, 403, { error: 'Admin API only available on localhost' })
          return
        }

        const url = new URL(req.url, 'http://localhost')
        const pathname = url.pathname

        try {
          if (req.method === 'GET' && pathname === '/__admin/maps') {
            const mapsJson = await readJsonFile<MapsJson>(mapsJsonPath)
            json(res, 200, { maps: mapsJson.maps })
            return
          }

          const mapIdMatch = pathname.match(/^\/__admin\/maps\/([^/]+)$/)
          if (req.method === 'GET' && mapIdMatch) {
            const mapId = decodeURIComponent(mapIdMatch[1])
            const mapsJson = await readJsonFile<MapsJson>(mapsJsonPath)
            const meta = mapsJson.maps.find((m) => m.id === mapId)
            const tmjPath = path.join(mapsDir, `${mapId}.tmj`)
            let tmj: unknown = null
            try {
              tmj = await readJsonFile(tmjPath)
            } catch {
              tmj = null
            }
            json(res, 200, {
              meta: meta ?? null,
              tmj,
              portals: mapsJson.portals?.[mapId] ?? [],
            })
            return
          }

          if (req.method === 'POST' && pathname === '/__admin/maps/save') {
            const body = await new Promise<SaveBody>((resolve, reject) => {
              const chunks: Buffer[] = []
              req.on('data', (chunk: Buffer) => chunks.push(chunk))
              req.on('end', () => {
                try {
                  resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')) as SaveBody)
                } catch (e) {
                  reject(e)
                }
              })
              req.on('error', reject)
            })
            const { mapMeta, tmj, portals } = body
            if (!mapMeta?.id || !tmj) {
              json(res, 400, { error: 'mapMeta.id and tmj required' })
              return
            }

            await fs.mkdir(mapsDir, { recursive: true })
            const tmjPath = path.join(mapsDir, `${mapMeta.id}.tmj`)
            await fs.writeFile(tmjPath, `${JSON.stringify(tmj, null, 2)}\n`, 'utf8')

            const mapsJson = await readJsonFile<MapsJson>(mapsJsonPath)
            const idx = mapsJson.maps.findIndex((m) => m.id === mapMeta.id)
            const entry = {
              id: mapMeta.id,
              displayName: mapMeta.displayName,
              fieldType: mapMeta.fieldType,
              sourceUrl: mapMeta.sourceUrl,
            }
            if (idx >= 0) mapsJson.maps[idx] = entry
            else mapsJson.maps.push(entry)

            if (!mapsJson.portals) mapsJson.portals = {}
            mapsJson.portals[mapMeta.id] = portals ?? []

            await fs.writeFile(mapsJsonPath, `${JSON.stringify(mapsJson, null, 2)}\n`, 'utf8')

            const portalExport = buildMapPortalsExport(mapsJson)
            await fs.writeFile(sharedPortalsPath, `${JSON.stringify(portalExport, null, 2)}\n`, 'utf8')

            const npcSql = generateNpcSql(mapMeta.id, portals ?? [])
            json(res, 200, { ok: true, npcSql })
            return
          }

          json(res, 404, { error: 'Not found' })
        } catch (err) {
          json(res, 500, { error: err instanceof Error ? err.message : String(err) })
        }
      })
    },
  }
}
