-- Map: prontera (Prontera)
-- Generated by map generator

-- Add/replace map on Prontera Warp Agent (Custom maps; idempotent by map_id)
update public.npc_definitions
set config = jsonb_set(
  config,
  '{destinations}',
  (
    select coalesce(jsonb_agg(elem), '[]'::jsonb)
    from jsonb_array_elements(coalesce(config->'destinations', '[]'::jsonb)) elem
    where elem->>'map_id' is distinct from 'prontera'
  ) || '[{"map_id": "prontera", "label": "Prontera", "x": 1600, "y": 1400, "category": "custom"}]'::jsonb
)
where id = 'prontera_warp';

-- NPC teleports from portals: none

-- NPC markers from TMJ npcs layer for map prontera (generated)
insert into public.npc_definitions (id, map_id, x, y, npc_type, label, config)
values
  (
    'prontera_kafra',
    'prontera',
    1840,
    1392,
    'storage',
    'Kafra',
    '{"facing":"down"}'::jsonb
  ),
  (
    'prontera_save',
    'prontera',
    1616,
    1456,
    'save',
    'Save Point',
    '{"facing":"down"}'::jsonb
  ),
  (
    'prontera_healer',
    'prontera',
    1392,
    1392,
    'healer',
    'Healer',
    '{"zenyCost":0,"facing":"down"}'::jsonb
  ),
  (
    'prontera_warp',
    'prontera',
    1616,
    1616,
    'teleport',
    'Warp Agent',
    '{"destinations":[{"x":480,"y":320,"label":"Prontera Field 01","map_id":"prt_fild01"},{"x":160,"y":160,"label":"Field (dev)","map_id":"field_01"},{"x":768,"y":112,"label":"Prontera Culvert","map_id":"prt_sewb1"}],"facing":"down"}'::jsonb
  ),
  (
    'prontera_job_master',
    'prontera',
    1616,
    816,
    'job_master',
    'Job Master',
    '{"offers":[{"jobId":"swordman","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"mage","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"archer","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"acolyte","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"merchant","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"thief","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"knight","zenyCost":0,"fromJobId":"swordman","requiredJobLevel":40,"requiredBaseLevel":40}],"facing":"down"}'::jsonb
  ),
  (
    'prontera_dungeon_guide',
    'prontera',
    2896,
    1392,
    'dungeon',
    'Dungeon Guide',
    '{"floors":["dun_f1","dun_f2","dun_f3","dun_f4","dun_f5"],"facing":"down"}'::jsonb
  ),
  (
    'prontera_weapon_dealer',
    'prontera',
    848,
    1840,
    'shop',
    'Weapon Dealer',
    '{"stock":[{"price":1200,"itemId":"knife"},{"price":1600,"itemId":"sword"},{"price":2400,"itemId":"falchion"},{"price":2900,"itemId":"blade"},{"price":3200,"itemId":"rapier"},{"price":3500,"itemId":"saber"},{"price":1000,"itemId":"rod"},{"price":2000,"itemId":"wand"},{"price":5000,"itemId":"staff"},{"price":2500,"itemId":"bow"},{"price":8000,"itemId":"great_bow"},{"price":15000,"itemId":"composite_bow"},{"price":2400,"itemId":"mace"},{"price":2900,"itemId":"club"},{"price":4500,"itemId":"smasher"},{"price":2800,"itemId":"axe"},{"price":5500,"itemId":"battle_axe"},{"price":2000,"itemId":"main_gauche"},{"price":2400,"itemId":"dagger"},{"price":3200,"itemId":"stiletto"}],"facing":"down"}'::jsonb
  ),
  (
    'prontera_armor_dealer',
    'prontera',
    1104,
    1840,
    'shop',
    'Armor Dealer',
    '{"stock":[{"price":10,"itemId":"cotton_shirt"},{"price":500,"itemId":"adventurers_suit"},{"price":500,"itemId":"silk_robe"},{"price":1200,"itemId":"wooden_mail"},{"price":2500,"itemId":"coat"},{"price":120,"itemId":"cap"},{"price":150,"itemId":"goggles"},{"price":100,"itemId":"flu_mask"},{"price":12000,"itemId":"helm"},{"price":800,"itemId":"wooden_shield"},{"price":600,"itemId":"buckler"},{"price":300,"itemId":"hooded_mantle"},{"price":800,"itemId":"mantle"},{"price":150,"itemId":"sandals"},{"price":400,"itemId":"shoes"},{"price":200,"itemId":"clip"},{"price":180,"itemId":"glove"}],"facing":"down"}'::jsonb
  ),
  (
    'prontera_tool_dealer',
    'prontera',
    2384,
    1840,
    'shop',
    'Tool Dealer',
    '{"buys":[{"price":2,"itemId":"jellopy"},{"price":3,"itemId":"fluff"},{"price":8,"itemId":"chrysalis"},{"price":26,"itemId":"worm_peeling"},{"price":4,"itemId":"sticky_mucus"},{"price":200,"itemId":"phracon"},{"price":9,"itemId":"red_herb"},{"price":25,"itemId":"iron_ore"},{"price":39,"itemId":"rat_tail"},{"price":27,"itemId":"animal_skin"},{"price":15,"itemId":"feather"},{"price":60,"itemId":"monsters_feed"},{"price":8,"itemId":"tooth_of_bat"},{"price":200,"itemId":"grape"}],"stock":[{"price":50,"itemId":"red_potion"}],"facing":"down"}'::jsonb
  )
on conflict (id) do update set
  map_id = excluded.map_id,
  x = excluded.x,
  y = excluded.y,
  npc_type = excluded.npc_type,
  label = excluded.label,
  config = excluded.config;
