-- Map: prontera (Prontera)
-- Generated by map admin

-- Add/replace map on Prontera Warp Agent (Custom maps; idempotent by map_id)
update public.npc_definitions
set config = jsonb_set(
  config,
  '{destinations}',
  (
    select coalesce(jsonb_agg(elem), '[]'::jsonb)
    from jsonb_array_elements(coalesce(config->'destinations', '[]'::jsonb)) elem
    where elem->>'map_id' is distinct from 'prontera'
  ) || '[{"map_id": "prontera", "label": "Prontera", "x": 320, "y": 320, "category": "custom"}]'::jsonb
)
where id = 'prontera_warp';

-- Return warp on map for map prontera (generated by map admin)
insert into public.npc_definitions (id, map_id, x, y, npc_type, label, config)
values
  (
    'prontera_return_warp',
    'prontera',
    320,
    320,
    'teleport',
    'Return to Prontera',
    '{"destinations":[{"map_id":"prontera","label":"Prontera","x":640,"y":360,"category":"standard"}]}'::jsonb
  )
on conflict (id) do update set
  map_id = excluded.map_id,
  x = excluded.x,
  y = excluded.y,
  npc_type = excluded.npc_type,
  label = excluded.label,
  config = excluded.config;

-- NPC teleports from portals: none

-- NPC markers from TMJ npcs layer for map prontera (generated by map admin)
insert into public.npc_definitions (id, map_id, x, y, npc_type, label, config)
values
  (
    'prontera_job_master',
    'prontera',
    446,
    73,
    'job_master',
    'Job Master',
    '{"offers":[{"jobId":"swordman","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"mage","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"archer","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"acolyte","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"merchant","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"thief","zenyCost":0,"fromJobId":"novice","requiredJobLevel":10,"requiredBaseLevel":1},{"jobId":"knight","zenyCost":0,"fromJobId":"swordman","requiredJobLevel":40,"requiredBaseLevel":40},{"jobId":"hunter","zenyCost":0,"fromJobId":"archer","requiredJobLevel":40,"requiredBaseLevel":40},{"jobId":"wizard","zenyCost":0,"fromJobId":"mage","requiredJobLevel":40,"requiredBaseLevel":40}],"facing":"down"}'::jsonb
  ),
  (
    'prontera_tool_dealer',
    'prontera',
    1353,
    1173,
    'shop',
    'Tool Dealer',
    '{"buys":[{"price":2,"itemId":"jellopy"},{"price":3,"itemId":"fluff"},{"price":8,"itemId":"chrysalis"},{"price":26,"itemId":"worm_peeling"},{"price":4,"itemId":"sticky_mucus"},{"price":200,"itemId":"phracon"},{"price":9,"itemId":"red_herb"},{"price":25,"itemId":"iron_ore"},{"price":39,"itemId":"rat_tail"},{"price":27,"itemId":"animal_skin"},{"price":15,"itemId":"feather"},{"price":60,"itemId":"monsters_feed"},{"price":8,"itemId":"tooth_of_bat"},{"price":200,"itemId":"grape"}],"stock":[{"price":50,"itemId":"red_potion"},{"price":120,"itemId":"blue_potion"}],"facing":"down"}'::jsonb
  ),
  (
    'prontera_dungeon_guide',
    'prontera',
    1797,
    1162,
    'dungeon',
    'Dungeon Guide',
    '{"floors":["dun_f1","dun_f2","dun_f3","dun_f4","dun_f5"],"facing":"down"}'::jsonb
  ),
  (
    'prontera_kafra',
    'prontera',
    1945,
    1336,
    'storage',
    'Kafra',
    '{"facing":"down"}'::jsonb
  ),
  (
    'prontera_save',
    'prontera',
    1371,
    1299,
    'save',
    'Save Point',
    '{"facing":"down"}'::jsonb
  ),
  (
    'prontera_healer',
    'prontera',
    1739,
    1490,
    'healer',
    'Healer',
    '{"zenyCost":0,"facing":"down"}'::jsonb
  ),
  (
    'prontera_warp',
    'prontera',
    1513,
    1491,
    'teleport',
    'Warp Agent',
    '{"destinations":[{"x":480,"y":320,"label":"Prontera Field 01","map_id":"prt_fild01"},{"x":160,"y":160,"label":"Field (dev)","map_id":"field_01"},{"x":768,"y":112,"label":"Prontera Culvert","map_id":"prt_sewb1"}],"facing":"down"}'::jsonb
  ),
  (
    'prontera_armor_dealer',
    'prontera',
    1407,
    1074,
    'shop',
    'Armor Dealer',
    '{"stock":[{"price":10,"itemId":"cotton_shirt"},{"price":500,"itemId":"adventurers_suit"},{"price":500,"itemId":"silk_robe"},{"price":1200,"itemId":"wooden_mail"},{"price":2500,"itemId":"coat"},{"price":120,"itemId":"cap"},{"price":150,"itemId":"goggles"},{"price":100,"itemId":"flu_mask"},{"price":12000,"itemId":"helm"},{"price":800,"itemId":"wooden_shield"},{"price":600,"itemId":"buckler"},{"price":300,"itemId":"hooded_mantle"},{"price":800,"itemId":"mantle"},{"price":150,"itemId":"sandals"},{"price":400,"itemId":"shoes"},{"price":200,"itemId":"clip"},{"price":180,"itemId":"glove"}],"facing":"down"}'::jsonb
  ),
  (
    'prontera_rental',
    'prontera',
    1464,
    1360,
    'rental',
    'Rental Shop',
    '{"facing":"down"}'::jsonb
  ),
  (
    'prontera_weapon_dealer',
    'prontera',
    1490,
    998,
    'shop',
    'Weapon Dealer',
    '{"stock":[{"price":1200,"itemId":"knife"},{"price":1600,"itemId":"sword"},{"price":1500,"itemId":"spear"},{"price":2400,"itemId":"falchion"},{"price":2900,"itemId":"blade"},{"price":3200,"itemId":"rapier"},{"price":3500,"itemId":"saber"},{"price":1000,"itemId":"rod"},{"price":2000,"itemId":"wand"},{"price":5000,"itemId":"staff"},{"price":2500,"itemId":"bow"},{"price":8000,"itemId":"great_bow"},{"price":15000,"itemId":"composite_bow"},{"price":2400,"itemId":"mace"},{"price":2900,"itemId":"club"},{"price":4500,"itemId":"smasher"},{"price":2800,"itemId":"axe"},{"price":5500,"itemId":"battle_axe"},{"price":2000,"itemId":"main_gauche"},{"price":2400,"itemId":"dagger"},{"price":3200,"itemId":"stiletto"}],"facing":"down"}'::jsonb
  ),
  (
    'prontera_rarity_armor_dealer',
    'prontera',
    1344,
    1856,
    'shop',
    'Rarity Armor Dealer',
    '{"stock":[{"price":100,"itemId":"padded_vest"},{"price":500,"itemId":"scout_mail"},{"price":2000,"itemId":"knight_plate"},{"price":8000,"itemId":"violet_cuirass"},{"price":25000,"itemId":"dragon_scale_mail"},{"price":80000,"itemId":"skyweave_robe"},{"price":250000,"itemId":"relic_guardplate"}],"shopLayout":"rarityTabs","facing":"down"}'::jsonb
  ),
  (
    'prontera_pvp_master',
    'prontera',
    1552,
    1648,
    'teleport',
    'PVP Master',
    '{"destinations":[{"x":640,"y":480,"label":"PVP Room","map_id":"pvp_room"}],"facing":"down","spriteKey":"job_master"}'::jsonb
  )
on conflict (id) do update set
  map_id = excluded.map_id,
  x = excluded.x,
  y = excluded.y,
  npc_type = excluded.npc_type,
  label = excluded.label,
  config = excluded.config;
