-- Map: prt_fild01 (Prontera Field 01)
-- Generated by scripts/generate-prt-fild01-map.mjs

-- Add/replace map on Prontera Warp Agent (Custom maps; idempotent by map_id)
update public.npc_definitions
set config = jsonb_set(
  config,
  '{destinations}',
  (
    select coalesce(jsonb_agg(elem), '[]'::jsonb)
    from jsonb_array_elements(coalesce(config->'destinations', '[]'::jsonb)) elem
    where elem->>'map_id' is distinct from 'prt_fild01'
  ) || '[{"map_id": "prt_fild01", "label": "Prontera Field 01", "x": 480, "y": 320, "category": "custom"}]'::jsonb
)
where id = 'prontera_warp';

insert into public.npc_definitions (id, map_id, x, y, npc_type, label, config)
values
  (
    'prt_fild01_kafra',
    'prt_fild01',
    400,
    400,
    'storage',
    'Kafra',
    '{}'::jsonb
  ),
  (
    'prt_fild01_warp',
    'prt_fild01',
    480,
    1536,
    'teleport',
    'Return Warp',
    '{"destinations":[{"map_id":"prontera","label":"Prontera","x":640,"y":360}]}'::jsonb
  )
on conflict (id) do update set
  map_id = excluded.map_id,
  x = excluded.x,
  y = excluded.y,
  npc_type = excluded.npc_type,
  label = excluded.label,
  config = excluded.config;
